sudo: enabled
language: generic
install: true

stages:
  - test
  - integration
  - package

jobs:
  include:

    #
    # Test
    #
    - name: Unit Tests
      stage: test
      env:
        - MIX_ENV=test
      script:
        - make deps compile test

    - name: Code Analysis
      stage: test
      script: make lint

    #
    # Integration
    #
    - name: Integration Tests
      stage: integration
      script: echo "NOT IMPLEMENTED"

    #
    # Package
    #
    - name: Docker Build Latest
      stage: package
      env:
        - DKR_TAG=latest
      script: make docker-push
      if: branch == "master"

    - name: Docker Build Latest
      stage: package
      env:
        - DKR_TAG=${TRAVIS_BRANCH}
      script: make docker-push
      if: branch != "master"

    - name: Docker Build Tag
      stage: package
      env:
        - DKR_TAG=$TRAVIS_TAG
      script: make docker-push
      if: tag
