sudo: enabled
language: generic
install: true

stages:
  - test
  - integration
  - package

jobs:
  include:

    #
    # Test
    #
    - stage: test
      env:
        - MIX_ENV=test
      script:
        - make deps compile test
    - stage: test
      script: make lint

    #
    # Integration
    #
    - stage: integration
      script: echo "NOT IMPLEMENTED"

    #
    # Package
    #
    - stage: package
      env:
        - DKR_TAG=latest
      script: make docker-push
      if: branch == "master"

    - stage: package
      env:
        - DKR_TAG=$$TRAVIS_BRANCH
      script: make docker-push
      if: branch != "master"

    - stage: package
      env:
        - DKR_TAG=$TRAVIS_TAG
      script: make docker-push
      if: tag
