sudo: enabled

stages:
  - compile
  - test

jobs:
  include:

    #
    # Compile
    #

    - stage: compile
      script:
        - MIX_ENV=test make deps compile
    - stage: compile
      script:
        - MIX_ENV=prod make deps compile

    #
    # Test
    #

    - stage: test
      script:
        - make test
    - stage: test
      script:
        - make lint