sudo: enabled
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

stages:
  - test

jobs:
  include:

    #
    # Test
    #

    - stage: test
      script:
        - MIX_ENV=test make deps compile test
    - stage: test
      script:
        - make lint