sudo: enabled
language: generic
stages:
  - test

jobs:
  include:

    #
    # Test
    #

    - stage: test
      script:
        - MIX_ENV=test make deps compile test
    - stage: test
      script:
        - make lint